### ISSUE TITLE
Naliczanie punktów za wielokrotne odpowiedzi + naprawa buga kontynuacji bez zaznaczonych 5 odpowiedzi

### ISSUE THREAD

**Issue by Sosek1** [IAESTE-AGH/SWIPE-AND-JOIN#12]
Naliczanie punktów za wielokrotne odpowiedzi nie działa trzeba napisać tego logikę i zapisać w context. Ponadto ogólnie trzeba przypisać odpowiedz do grup. 

Trzeba też naprawić buga gdy 5 odp nie jest zaznaczone.

Dodać też transition żeby zaznaczanie i odznaczanie nie było gwałtowne

**Comment by Szymon-Nowaq** [comment]
Bierę 😎
