### ISSUE TITLE
Efekt swipowania 

### ISSUE THREAD

**Issue by Sosek1** [IAESTE-AGH/SWIPE-AND-JOIN#13]
Jeśli chodzi o profile to trzeba wymyślić jak odwzorować tinderowe swipowanie.
Po przeciągnięciu karty profilu w lewą stronę kółko ikonki X ma wypełniać się nie gwałtownie kolorem a sama ikonka ma zmienić kolor na biały. Analogicznie z ikonką lika jeśli karta profilu jest po prawej stronie ekranu ikonka lika ma zmienić stopniowo kolor. Jeśli ktoś nie korzystał z tindera i nie wie jak to wygląda proszę pobrać i zobaczyć oczywiście w celach pracy czas na rizzowanie będzie jak skończymy.

**Comment by Szymon-Nowaq** [comment]
Biorę 😎
